name: Deploy to Github Pages
on:
  push:
    branches:
      - "release"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: build-publish
        uses: bitovi/github-actions-react-to-github-pages@v1.2.0
        with:
          path: dist # change to your build folder
