name: Deploy to Github Pages
on:
  push:
    branches:
      - "release"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Dependency
        run: npm install
        shell: bash
      - name: Build
        run: npm run build
        shell: bash
      - name: Deploy
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        env:
          WELCOME: "ssh scp ssh pipelines"
          LASTSSH: "Doing something after copying"
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          user: ${{ secrets.HOSTINGER_USERNAME }}
          pass: ${{ secrets.HOSTINGER_PASSWORD }}
          port: ${{ secrets.HOSTINGER_PORT }}
          scp: |
            './dist/*' => /home/u835893703/domains/fullstackbd.com/public_html/sample
      