name: Deploy to Github Pages
on:
  push:
    branches:
      - "release"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build
        run: npm run build
        shell: bash
      - name: SSH
        uses: ErenKrt/ssh-push@main
        with:
          HOST: ${{ secrets.HOSTINGER_HOST }}
          PORT: ${{ secrets.HOSTINGER_PORT }} 
          USERNAME: ${{ secrets.HOSTINGER_USERNAME }}
          PRIVATE_KEY:  ${{ secrets.HOSTINGER_PRIVATE_KEY }}
          SOURCE: "dist/"
          OUTDIR: "/home/u835893703/domains/fullstackbd.com/public_html/sample"
          #exclude: |
          #  *.exe
          #scripts: |
          #  cd /home/eren/test && unzip myZipname.zip && rm -r *.zip
          #  cat /home/eren/test/index.js
          #zipname: "myZipname.zip"
